
USE QuanLyKTX

CREATE TABLE SINHVIEN(
    MA_SV VARCHAR(10) PRIMARY KEY NOT NULL,
	HOTEN_SV NVARCHAR(MAX) NOT NULL,
	GIOITINH_SV NVARCHAR(5) NOT NULL,
	NAMSINH_SV INT NOT NULL,
	SODT_SV VARCHAR(10) NOT NULL,
	QUEQUAN_SV NVARCHAR(MAX) NOT NULL,
	MAIL_SV VARCHAR(50)
)

CREATE TABLE NHANVIEN(
    MA_NV VARCHAR(10) PRIMARY KEY NOT NULL,
	HOTEN_NV NVARCHAR(MAX) NOT NULL,
	GIOITINH_NV NVARCHAR(5) NOT NULL,
	SODT_NV VARCHAR(10) NOT NULL,
	NAMSINH_NV INT NOT NULL,
	QUEQUAN_NV NVARCHAR(MAX) NOT NULL
)

CREATE TABLE PHONGKTX(
    MA_PHONGKTX VARCHAR(10)PRIMARY KEY NOT NULL,
	DAY_NHA VARCHAR(10) NOT NULL,
	KHU_NHA VARCHAR(10) NOT NULL,
	CHUC_NANG NVARCHAR(50) NOT NULL,
	DTICH_PHONGKTX FLOAT,
	SO_GIUONG INT,
	CON_TRONG INT
)

CREATE TABLE HOPDONG(
    MA_HOPDONG VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_HOPDONG NVARCHAR(MAX) NOT NULL,
	MA_NV VARCHAR(10) CONSTRAINT FK_HOPD_NGLAP FOREIGN KEY REFERENCES NHANVIEN(MA_NV) NOT NULL,
	MA_SV VARCHAR(10) CONSTRAINT FK_HOAD_NGTHUE FOREIGN KEY REFERENCES SINHVIEN(MA_SV) NOT NULL,
	NGAYLAP_HOPDONG DATE NOT NULL,
	NGAYHET_HOPDONG DATE NOT NULL
)

CREATE TABLE HOADON(
    MA_HOADON VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_HOADON NVARCHAR(MAX) NOT NULL,
	NGLAP_HOADO VARCHAR(10) CONSTRAINT FK_HOAD_NGLHD FOREIGN KEY REFERENCES NHANVIEN(MA_NV) NOT NULL,
	MA_SV VARCHAR(10) NOT NULL,
	PHONGKTX VARCHAR(10) NOT NULL,
	NGAYLAP_HOADON DATE NOT NULL
)

CREATE TABLE SOTHEODOI(
    MA_SO VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_SO NVARCHAR(MAX) NOT NULL,
	NG_KHENPHAT VARCHAR(10) CONSTRAINT FK_STD_NGKP FOREIGN KEY REFERENCES SINHVIEN(MA_SV) NOT NULL,
	PHGKTX VARCHAR(10) CONSTRAINT FK_STD_PHGKTX FOREIGN KEY REFERENCES PHONGKTX(MA_PHONGKTX) NOT NULL,
	NG_GHISO VARCHAR(10) CONSTRAINT FK_STD_NGGHI FOREIGN KEY REFERENCES NHANVIEN(MA_NV) NOT NULL,
	MA_KHENPHAT VARCHAR(10) NOT NULL,
	TEN_KHENPHAT NVARCHAR(MAX) NOT NULL,
	NGAYGHI_SO DATE NOT NULL
)

CREATE TABLE BAOCAO_THONGKE(
    MA_BCTK VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_BCTK NVARCHAR(50) NOT NULL,
	NGLAP_BCTK VARCHAR(10) CONSTRAINT FK_BCTK_NGLAP FOREIGN KEY REFERENCES NHANVIEN(MA_NV) NOT NULL,
	NGAYLAP_BCTK DATE NOT NULL
)

CREATE TABLE THANNHAN(
    MA_SV VARCHAR(10) NOT NULL,
	HOTEN_TN NVARCHAR(MAX) NOT NULL,
	QUAN_HE NVARCHAR(20) NOT NULL,
	GIOITINH_TN NVARCHAR(5) NOT NULL,
	SODT_TN VARCHAR(10) NOT NULL,
	PRIMARY KEY (MA_SV)
)

CREATE TABLE DIENNUOC(
    MA_HOADON VARCHAR(10) NOT NULL,
	SODIEN INT NOT NULL,
	SOKHOINUOC INT NOT NULL,
	DON_GIA MONEY NOT NULL,
	TONG_TIEN MONEY NOT NULL
	PRIMARY KEY (MA_HOADON, TONG_TIEN)
)